import type { VercelRequest, VercelResponse } from '@vercel/node';

interface School {
  id: string;
  name: string;
  nameLocal?: string;
  address: string;
  lat: number;
  lng: number;
  medium: string[];
  type: '1AB' | '1C' | 'Type2' | 'Type3';
  zone: string;
  contactPhone?: string;
}

const schools: School[] = [
  {
    id: 'sch-001',
    name: "St. Cecilia's Girls' College",
    nameLocal: 'புனித செசிலியா பெண்கள் கல்லூரி',
    address: "St. Anthony's Street, Puliyanthivu, Batticaloa",
    lat: 7.7164,
    lng: 81.6976,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2345',
  },
  {
    id: 'sch-002',
    name: "St. Michael's College National School",
    nameLocal: 'புனித மிக்கேல் கல்லூரி தேசிய பாடசாலை',
    address: 'Central Road, Batticaloa',
    lat: 7.7155,
    lng: 81.6985,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2456',
  },
  {
    id: 'sch-003',
    name: "Vincent Girls' High School",
    nameLocal: 'வின்சென்ட் மகளிர் உயர்தர பாடசாலை',
    address: 'Lake Road, Puliyanthivu, Batticaloa',
    lat: 7.7142,
    lng: 81.6995,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2567',
  },
  {
    id: 'sch-004',
    name: 'Methodist Central College',
    nameLocal: 'மெதடிஸ்த மத்திய கல்லூரி',
    address: 'Puliyanthivu, Batticaloa',
    lat: 7.7135,
    lng: 81.7015,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2678',
  },
  {
    id: 'sch-005',
    name: 'Mahajana College',
    nameLocal: 'மகாஜனா கல்லூரி',
    address: 'New Road, Batticaloa',
    lat: 7.7185,
    lng: 81.6952,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2789',
  },
  {
    id: 'sch-006',
    name: 'Batticaloa Hindu College',
    nameLocal: 'மட்டக்களப்பு இந்துக் கல்லூரி',
    address: 'Trincomalee Road, Batticaloa',
    lat: 7.7190,
    lng: 81.6942,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2890',
  },
  {
    id: 'sch-007',
    name: "St. Joseph's College",
    nameLocal: 'புனித சூசையப்பர் கல்லூரி',
    address: 'Main Street, Batticaloa',
    lat: 7.7150,
    lng: 81.6970,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 2901',
  },
  {
    id: 'sch-008',
    name: 'Shivananda National School',
    nameLocal: 'சிவானந்தா தேசிய பாடசாலை',
    address: 'Kallady, Batticaloa',
    lat: 7.7052,
    lng: 81.7125,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 3012',
  },
  {
    id: 'sch-009',
    name: 'Al-Azhar Vidyalaya',
    nameLocal: 'அல்-அஸ்ஹர் வித்தியாலயம்',
    address: 'New Road, Batticaloa',
    lat: 7.7215,
    lng: 81.6925,
    medium: ['Tamil', 'English'],
    type: '1C',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 3123',
  },
  {
    id: 'sch-010',
    name: 'Kallady Ramakrishna Mission Vidyalayam',
    nameLocal: 'கல்லடி ஸ்ரீ இராமகிருஷ்ண மிஷன் வித்தியாலயம்',
    address: 'Lady Manning Drive, Kallady, Batticaloa',
    lat: 7.7085,
    lng: 81.7105,
    medium: ['Tamil', 'English'],
    type: '1C',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 3234',
  },
  {
    id: 'sch-011',
    name: 'Aanaipanthy Sri Sithy Vinayagar Vidyalayam',
    nameLocal: 'ஆனைப்பந்தி ஸ்ரீ சித்தி விநாயகர் வித்தியாலயம்',
    address: 'Aanaipanthy, Batticaloa',
    lat: 7.7255,
    lng: 81.6912,
    medium: ['Tamil'],
    type: 'Type2',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 3345',
  },
  {
    id: 'sch-012',
    name: 'Vivekananda Vidyalaya',
    nameLocal: 'விவேகானந்தா வித்தியாலயம்',
    address: 'Urani, Batticaloa',
    lat: 7.7280,
    lng: 81.6890,
    medium: ['Tamil'],
    type: '1C',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 3456',
  },
  {
    id: 'sch-013',
    name: "St. Mary's Convent School",
    nameLocal: 'புனித மரியாள் கன்னியர் மடம் பாடசாலை',
    address: 'Convent Road, Puliyanthivu, Batticaloa',
    lat: 7.7160,
    lng: 81.6980,
    medium: ['Tamil', 'English'],
    type: 'Type2',
    zone: 'Batticaloa',
    contactPhone: '+94 65 222 3567',
  },
  {
    id: 'sch-014',
    name: 'Kallady Veloor Sri Sakthi Vidyalayam',
    nameLocal: 'கல்லடி வேலூர் ஸ்ரீ சக்தி வித்தியாலயம்',
    address: 'Veloor, Kallady, Batticaloa',
    lat: 7.7010,
    lng: 81.7150,
    medium: ['Tamil'],
    type: 'Type2',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-015',
    name: 'Urani Saraswathi Vidyalayam',
    nameLocal: 'ஊரணி சரஸ்வதி வித்தியாலயம்',
    address: 'Urani, Batticaloa',
    lat: 7.7315,
    lng: 81.6855,
    medium: ['Tamil'],
    type: 'Type2',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-016',
    name: 'Amirthakali Sri Siddhi Vinayagar Vidyalayam',
    nameLocal: 'அமிர்தகழி ஸ்ரீ சித்தி விநாயகர் வித்தியாலயம்',
    address: 'Amirthakali, Batticaloa',
    lat: 7.7350,
    lng: 81.6905,
    medium: ['Tamil'],
    type: 'Type2',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-017',
    name: 'Thiraimadu Sri Krishna Vidyalayam',
    nameLocal: 'திரைமடு ஸ்ரீ கிருஷ்ணா வித்தியாலயம்',
    address: 'Thiraimadu, Batticaloa',
    lat: 7.7410,
    lng: 81.6795,
    medium: ['Tamil'],
    type: 'Type3',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-018',
    name: 'Navatkudah Namagal Vidyalayam',
    nameLocal: 'நாவற்குடா நாமகள் வித்தியாலயம்',
    address: 'Navatkudah, Batticaloa',
    lat: 7.6950,
    lng: 81.7210,
    medium: ['Tamil'],
    type: 'Type2',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-019',
    name: 'Kattankudy Central College (National School)',
    nameLocal: 'காத்தான்குடி மத்திய கல்லூரி',
    address: 'New Road, Kattankudy',
    lat: 7.6850,
    lng: 81.7260,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 224 5678',
  },
  {
    id: 'sch-020',
    name: 'Meera Balika Maha Vidyalaya',
    nameLocal: 'மீரா பாலிகா மகா வித்தியாலயம்',
    address: 'Beach Road, Kattankudy',
    lat: 7.6820,
    lng: 81.7285,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
    contactPhone: '+94 65 224 5789',
  },
  {
    id: 'sch-021',
    name: 'Al-Hira Maha Vidyalaya',
    nameLocal: 'அல்-ஹிரா மகா வித்தியாலயம்',
    address: 'Division 6, Kattankudy',
    lat: 7.6780,
    lng: 81.7290,
    medium: ['Tamil'],
    type: '1C',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-022',
    name: 'Arayampathy Ramakrishna Mission Maha Vidyalayam',
    nameLocal: 'ஆரையம்பதி ஸ்ரீ இராமகிருஷ்ண மிஷன் மகா வித்தியாலயம்',
    address: 'Main Road, Arayampathy',
    lat: 7.6650,
    lng: 81.7350,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-023',
    name: 'Eravur Al-Ashraq National School',
    nameLocal: 'ஏறாவூர் அல்-அஷ்ரக் தேசிய பாடசாலை',
    address: 'Main Street, Eravur',
    lat: 7.7750,
    lng: 81.6050,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-024',
    name: 'Eravur Rahmaniya Maha Vidyalaya',
    nameLocal: 'ஏறாவூர் ரஹ்மானியா மகா வித்தியாலயம்',
    address: 'Market Road, Eravur',
    lat: 7.7720,
    lng: 81.6080,
    medium: ['Tamil'],
    type: '1C',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-025',
    name: 'Chenkalady Central College',
    nameLocal: 'செங்கலடி மத்திய கல்லூரி',
    address: 'Badulla Road, Chenkalady',
    lat: 7.7950,
    lng: 81.5850,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-026',
    name: 'Kommathurai Sri Murugan Vidyalayam',
    nameLocal: 'கொம்மாதுறை ஸ்ரீ முருகன் வித்தியாலயம்',
    address: 'Kommathurai, Chenkalady',
    lat: 7.8100,
    lng: 81.5750,
    medium: ['Tamil'],
    type: 'Type2',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-027',
    name: 'Paddiruppu National School',
    nameLocal: 'பட்டிருப்பு தேசிய கல்லூரி',
    address: 'Main Road, Kaluwanchikudy',
    lat: 7.5300,
    lng: 81.7850,
    medium: ['Tamil', 'English'],
    type: '1AB',
    zone: 'Batticaloa',
  },
  {
    id: 'sch-028',
    name: 'Kokkadichcholai Sri Ramakrishna Vidyalayam',
    nameLocal: 'கொக்கட்டிச்சோலை ஸ்ரீ இராமகிருஷ்ணா வித்தியாலயம்',
    address: 'Main Road, Kokkadichcholai',
    lat: 7.6450,
    lng: 81.6500,
    medium: ['Tamil'],
    type: '1C',
    zone: 'Batticaloa',
  },
];

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Cache-Control', 'public, max-age=3600, s-maxage=3600, stale-while-revalidate=86400');
  return res.status(200).json(schools);
}
